### ISSUE TITLE
trends/seasonality

### ISSUE THREAD

**Issue by aspina7** [aspina7/EpiconceptIPD#2]
obviously have no clue what im talking about - but can we jump right in to regression without addressing general trend and seasonality? Looks like goes in 4.5 year cycles with minicycles within....

**Comment by lukric** [comment]
due to small numbers i think its best to use anual number of cases (due to long period of data we have enough time points - although 12 in each period are suggested, and also have a real good amount of observations per year - here a number of about 100 obs per time point is desirable. anyways this numbers somehow come a little out of the blue). we could write a small section about adding seasonality to monthly data?

**Comment by aspina7** [comment]
Maybe just a note somewhere at the end? Or appendix? and a short example of code, nothing long though!
